services:
  db:
    image: postgres
    container_name: db-api-redis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-redis
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: cache-api-redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: api-redis
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/api-redis
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres