apiVersion: v1
kind: Service
metadata:
  name: api-redis
  namespace: apiredis
spec:
  selector:
    app: api-redis
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort